### ISSUE TITLE
AssertionError on calling `run_simulations(dmaps)` 01-Ray-Tasks.ipynb

### ISSUE THREAD

**Issue by MatusGasparik** [anyscale/academy#53]
I get an `AssertionError` when calling `run_simulations(dmaps)` in the [01-Ray-Tasks.ipynb](ray-crash-course/01-Ray-Tasks.ipynb):

I am running locally from a conda env (followed exactly the Setup section of the [README](README.md)). The simulation seems to run though unaffected by the exception...

Here is the output of the traceback including a related warnings:

```
WARNING:param.dynamic_operation: Callable raised "AssertionError('New option id 2951106455928858 does not match any option trees in Store.custom_options.')".
Invoked as dynamic_operation(counter=0)
WARNING:param.dynamic_operation: Callable raised "AssertionError('New option id 2951106455928858 does not match any option trees in Store.custom_options.')".
Invoked as dynamic_operation(counter=0)
Traceback (most recent call last):
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/plotting/util.py", line 275, in get_plot_frame
    return map_obj[key]
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1341, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1110, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 714, in __call__
    ret = self.callable(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1042, in dynamic_operation
    key, obj = resolve(key, kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1031, in resolve
    return key, map_obj[key]
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1341, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1110, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 714, in __call__
    ret = self.callable(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1043, in dynamic_operation
    return apply(obj, *key, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1035, in apply
    processed = self._process(element, key, kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1019, in _process
    return self.p.operation(element, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 625, in <lambda>
    dmap = Dynamic(obj, operation=lambda obj, **dynkwargs: obj.opts(*args, **kwargs),
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 37, in pipelined_call
    return __call__(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 573, in __call__
    return self._dispatch_opts( *args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 577, in _dispatch_opts
    return self._base_opts(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 656, in _base_opts
    return self._obj.options(*new_args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/dimension.py", line 1307, in options
    obj = obj.opts._dispatch_opts(expanded, backend=backend, clone=clone)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 577, in _dispatch_opts
    return self._base_opts(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 653, in _base_opts
    return opts.apply_groups(self._obj, **dict(kwargs, **new_kwargs))
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 244, in apply_groups
    obj = cls._apply_groups_to_backend(obj, backend_opts, backend, clone)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 169, in _apply_groups_to_backend
    return StoreOptions.set_options(obj_handle, options, backend=backend)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/options.py", line 1843, in set_options
    applied = cls.propagate_ids(obj, match_id, new_id, compositor_applied+list(spec.keys()), backend=backend)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/options.py", line 1511, in propagate_ids
    % new_id)
AssertionError: New option id 2951106455928858 does not match any option trees in Store.custom_options.

WARNING:param.dynamic_operation: Callable raised "AssertionError('New option id 4286036670735367693583064832671926448157 does not match any option trees in Store.custom_options.')".
Invoked as dynamic_operation(counter=0)
WARNING:param.dynamic_operation: Callable raised "AssertionError('New option id 4286036670735367693583064832671926448157 does not match any option trees in Store.custom_options.')".
Invoked as dynamic_operation(counter=0)
Traceback (most recent call last):
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/plotting/util.py", line 275, in get_plot_frame
    return map_obj[key]
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1341, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1110, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 714, in __call__
    ret = self.callable(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1042, in dynamic_operation
    key, obj = resolve(key, kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1031, in resolve
    return key, map_obj[key]
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1341, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1110, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/spaces.py", line 714, in __call__
    ret = self.callable(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1043, in dynamic_operation
    return apply(obj, *key, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1035, in apply
    processed = self._process(element, key, kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 1019, in _process
    return self.p.operation(element, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 625, in <lambda>
    dmap = Dynamic(obj, operation=lambda obj, **dynkwargs: obj.opts(*args, **kwargs),
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 37, in pipelined_call
    return __call__(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 573, in __call__
    return self._dispatch_opts( *args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 577, in _dispatch_opts
    return self._base_opts(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 656, in _base_opts
    return self._obj.options(*new_args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/dimension.py", line 1307, in options
    obj = obj.opts._dispatch_opts(expanded, backend=backend, clone=clone)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 577, in _dispatch_opts
    return self._base_opts(*args, **kwargs)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/accessors.py", line 653, in _base_opts
    return opts.apply_groups(self._obj, **dict(kwargs, **new_kwargs))
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 244, in apply_groups
    obj = cls._apply_groups_to_backend(obj, backend_opts, backend, clone)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/util/__init__.py", line 169, in _apply_groups_to_backend
    return StoreOptions.set_options(obj_handle, options, backend=backend)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/options.py", line 1843, in set_options
    applied = cls.propagate_ids(obj, match_id, new_id, compositor_applied+list(spec.keys()), backend=backend)
  File "/Users/matus/miniconda3/envs/anyscale-academy/lib/python3.7/site-packages/holoviews/core/options.py", line 1511, in propagate_ids
    % new_id)
AssertionError: New option id 4286036670735367693583064832671926448157 does not match any option trees in Store.custom_options.
```

**Comment by Saberfish** [comment]
Hi , I have the same problem with you. But it is fixed.
You can open the enviroment.yml and change "ray[all]==0.8.7" to "ray[all]==1.2.0".
That should work.

**Comment by MatusGasparik** [comment]
> Hi , I have the same problem with you. But it is fixed.
> You can open the enviroment.yml and change "ray[all]==0.8.7" to "ray[all]==1.2.0".
> That should work.

According to `environment.yml` the required version of `ray` if 1.2 or higher:
```
- pip:
    - ray[all] >= 1.2
```

And my version is:

`conda list -n anyscale-academy ray`

```
# packages in environment at /Users/matus/miniconda3/envs/anyscale-academy:
#
# Name                    Version                   Build  Channel
ray                       1.4.0                    pypi_0    pypi
```
